### PR TITLE
OAK-10465 : backported changes to 1.22 branch

### PR DESCRIPTION
**Pull request by rishabhdaim**

### CODE REVIEW

**Review by reschke — CHANGES_REQUESTED** [review]
We don't need a separate PR for this; we can just cherry-pick the change and apply it to the branch,

**Comment by rishabhdaim** [comment]
I created a separate PR because the changes are a bit different for the `1.22` branch.
Maven scope is `compile` for `1.22` whereas it is `provided` for the `trunk`.

**Comment by reschke** [comment]
Ah, I missed that.

**Review by reschke — APPROVED** [review]

**Comment by reschke** [comment]
@rishabhdaim - could you please update the fixVersion info in the ticket?

**Comment by rishabhdaim** [comment]
> @rishabhdaim - could you please update the fixVersion info in the ticket?

done.

**Pull request merged**
