### PR TITLE
fix javadoc

### PR DESCRIPTION
**Pull request by stefan-egli**

### CODE REVIEW

**Comment by stefan-egli** [comment]
@anchela , can you please approve this change? this failed `mvn javadoc:javadoc`

**Comment by stefan-egli** [comment]
Applied to trunk at http://svn.apache.org/viewvc?rev=1886624&view=rev

**Review by anchela — APPROVED** [review]
oh.... thanks a lot @stefan-egli  for spotting and fixing.... that's an oversight from my side. sorry for that

**Comment by stefan-egli** [comment]
no worries, thx for verifying. Closing this PR then.

**Pull request closed without merging**
