### PR TITLE
OAK-10765 : use removeEldestEntry api for linkedhashmap to remove old…

### PR DESCRIPTION
**Pull request by rishabhdaim**
… entries

### CODE REVIEW

**Review by stefan-egli — COMMENTED** [review]
+1, just wondering if the changes in RevisionsCommand are related/needed?

**Comment by rishabhdaim** [comment]
I have added more loggers to RevisionsCommand to log the message from the mentioned classes.

**Comment by stefan-egli** [comment]
but unrelated to OAK-10765 I assume?

**Comment by rishabhdaim** [comment]
Yes, unrelated to OAK-10765.

**Review by stefan-egli — APPROVED** [review]

**Pull request merged**
