### PR TITLE
OAK-10486 : Resolution of inherited groups may terminate pre-maturely for external users

### PR DESCRIPTION
**Pull request by anchela**
hi @reschke , i would very much appreciate if you had time to review this.

### CODE REVIEW

**Review by reschke — COMMENTED** [review]
So if I understand correctly, the problem was the early return in line 73? That would imply that swapping line 72..74 with 75..77 would fix it, too?

**Comment by mbaedke** [comment]
> So if I understand correctly, the problem was the early return in line 73? That would imply that swapping line 72..74 with 75..77 would fix it, too?

That is also my understanding. The two new testcases agree, too.

**Review by reschke — APPROVED** [review]

**Review by mbaedke — APPROVED** [review]

**Comment by anchela** [comment]
@reschke , to answer your questions: yes and yes. do you agree that the approach chosen in the PR is equivalent? i find it easier to understand as the decision on what iterator to read from, when to move on to the next and when all iterators have been processed is kept in a single place.

**Comment by mbaedke** [comment]
It is definitely equivalent.

> i find it easier to understand as the decision on what iterator to read from, when to move on to the next and when all iterators have been processed is kept in a single place.

And that is a good point.

**Comment by reschke** [comment]
bq. @reschke , to answer your questions: yes and yes. do you agree that the approach chosen in the PR is equivalent? i find it easier to understand as the decision on what iterator to read from, when to move on to the next and when all iterators have been processed is kept in a single place.

Yes, they look equivalent. I just wanted to double-check that I had understood the problem.

**Pull request merged**
