### PR TITLE
OAK-9548 changed the blockId parameter to match blockid parameter in azure Put Block API spec

### PR DESCRIPTION
**Pull request by adamcin**
Azurite, the local nodejs-based Azure Storage Simulator, uses case-sensitive parameter matching when performing lookups based on autogen OpenAPI specs. This change will make it possible to use Azurite as a near fully-functional, fully-local replacement for a real Azure storage account for development and testing of Direct Binary Access related features.

### CODE REVIEW

**Comment by adamcin** [comment]
@mattvryan  might you have an opportunity to review this PR?

**Comment by mreutegg** [comment]
This looks reasonable to me. @mattvryan any concerns merging this?

**Comment by mattvryan** [comment]
I'll take a look.  Thanks for the PR!

**Review by mattvryan — APPROVED** [review]
LGTM.  Thanks for the fix.

**Pull request merged**
