### PR TITLE
OAK-11247: Migrated groovy test files to Java

### PR DESCRIPTION
**Pull request by Amoratinos**
Migrated Groovy test files in oak-pojosr package to Java.

Asserts were changed to use junit assert methods imported statically.

### CODE REVIEW

**Review by anchela — APPROVED** [review]
hi @Amoratinos , i just looked at the SecurityProviderRegistrationTest and that one looks good if we conclude that we want to keep the existing module and the way it's running tests... which is probably what we can achieve with limited effort.
an alternative approach would be to rewrite the intention of the tests within the oak modules they belong to, get rid of the mocking and use PaxExam to build ITs that accurately reflect running oak in a OSGi setup like we have it in Adobe AEM. but maybe that's too much of an effort compared to the gain.

**Comment by Amoratinos** [comment]
> use PaxExam to build ITs that accurately reflect running oak in a OSGi setup like we have it in Adobe AEM. but maybe that's too much of an effort compared to the gain.

I'm fine to take that task with me but I think that's a broader scope of the task. Specially from reviewer's point of view it would need to invest more time and effort to go over the changes. If it's fine for you I'll create a new ticket asking to change that test to use PaxExam.

**Review by reschke — APPROVED** [review]
I really can't review.

It the Groovy dependency is gone, and integration tests are passing ("-PintegrationTesting"), this should be good.

**Comment by reschke** [comment]
@anchela  - paxExam is abandoned; we should not use it in "new" code (see https://mvnrepository.com/artifact/org.ops4j.pax.exam/pax-exam)

**Comment by Amoratinos** [comment]
@reschke I suppose you wanted to mention @anchela  😅 

At least the pax exam repo seems somehow mantained https://github.com/ops4j/org.ops4j.pax.exam/activity 

I ran the integrationTesting locally and it went through without issues

**Comment by reschke** [comment]
@anchela - time to merge?

**Comment by anchela** [comment]
yep

**Pull request merged**
