### PR TITLE
OAK-11248 : reapply changes of #1845 (which got reverted in #1853)

### PR DESCRIPTION
**Pull request by stefan-egli**

### CODE REVIEW

**Comment by stefan-egli** [comment]
@rishabhdaim can you please review? thx!

**Comment by stefan-egli** [comment]
@rishabhdaim , friendly reminder : could you please review this one? It was reverted before 1.72 unfortunately, and needs to be reapplied now for 1.74, thx!

**Review by rishabhdaim — APPROVED** [review]

**Comment by stefan-egli** [comment]
there was a test failure 
```
[INFO] Running org.apache.jackrabbit.oak.plugins.document.VersionGarbageCollectorIT
Cancelling nested steps due to timeout
Sending interrupt signal to process
```

looks like the test takes too long and we should maybe improve that. but that's orthogonal to this PR. so going to merge next

**Comment by stefan-egli** [comment]
>  but that's orthogonal to this PR

created https://issues.apache.org/jira/browse/OAK-11282

**Pull request merged**
