### PR TITLE
OAK-10727 : log revisionDetailedGcType in VersionGarbageCollector con…

### PR DESCRIPTION
**Pull request by stefan-egli**
…structor

### CODE REVIEW

**Comment by stefan-egli** [comment]
@rishabhdaim  wdyt?

**Review by Joscorbe — APPROVED** [review]
I think this is a good idea.

**Comment by rishabhdaim** [comment]
I wonder if I shouldn't add this to `VersionGCStats` so it gets logged along with other stats.

**Review by rishabhdaim — APPROVED** [review]

**Comment by stefan-egli** [comment]
+1 to adding it also to VersionGCStats - we can still see which one turns out more/how useful and adjust along the way in case

**Pull request merged**
