### PR TITLE
OAK-10961: Remove usage of Guava Predicate interface

### PR DESCRIPTION
**Pull request by reschke**

### CODE REVIEW

**Review by nfsantos — APPROVED** [review]
It would be interesting to check if the final artifacts become smaller with these changes. This PR replaces a lot of anonymous inner classes by lambdas, for which the compiler does not need to generate a class as all the wiring is done at runtime. So I expect a small reduction in the size of the compiled code.

**Comment by reschke** [comment]
I can check this later today.

**Comment by nfsantos** [comment]
Just a quick lookup, this PR removes 4 anonymous inner classes in `EffectiveNodeTypeImpl`. Here are the sizes of the current trunk: 
```
16286 26 Jul 10:57 ./oak-core/target/classes/org/apache/jackrabbit/oak/plugins/nodetype/EffectiveNodeTypeImpl.class
 1365 26 Jul 10:57 ./oak-core/target/classes/org/apache/jackrabbit/oak/plugins/nodetype/EffectiveNodeTypeImpl$4.class
 1368 26 Jul 10:57 ./oak-core/target/classes/org/apache/jackrabbit/oak/plugins/nodetype/EffectiveNodeTypeImpl$2.class
 1341 26 Jul 10:57 ./oak-core/target/classes/org/apache/jackrabbit/oak/plugins/nodetype/EffectiveNodeTypeImpl$3.class
 1344 26 Jul 10:57 ./oak-core/target/classes/org/apache/jackrabbit/oak/plugins/nodetype/EffectiveNodeTypeImpl$1.class
```
So 1300 bytes each anonymous class, not too bad if we no longer need to generate and store these classes.

**Comment by reschke** [comment]
I tried oak-core with the changes for OAK-10945 (Function inlining):


ca12732421aafc2881706a2c5849b3e460156b92

1773102

0bb3dde9b1fe40d8428cb30bc231c7faf54cc923

1765091

**Comment by nfsantos** [comment]
> I tried [oak-core](https://issues.apache.org/jira/browse/OAK-core) with the changes for [OAK-10945](https://issues.apache.org/jira/browse/OAK-10945) (Function inlining):
> 
> [ca12732](https://github.com/apache/jackrabbit-oak/commit/ca12732421aafc2881706a2c5849b3e460156b92)
> 
> 1773102
> 
> [0bb3dde](https://github.com/apache/jackrabbit-oak/commit/0bb3dde9b1fe40d8428cb30bc231c7faf54cc923)
> 
> 1765091

Not huge, but it's a step in the right direction, especially because the code with lambdas is cleaner.

**Comment by reschke** [comment]
(Potential) reviewers: I'll let that sit until end of week and then merge.

**Review by thomasmueller — APPROVED** [review]

**Pull request merged**
