### PR TITLE
Clarified a pitfall with --merge-paths

### PR DESCRIPTION
**Pull request by sbluhm**
Clarified a pitfall with a merge operation, should a node be renamed.

### CODE REVIEW

**Comment by sbluhm** [comment]
@stefan-egli , any chance of merging this PR? It has been in my queue for a while.

**Comment by jsedding** [comment]
@sbluhm I believe this pitfall is only true for referenceable nodes. Other nodes don't have a UUID property, and thus are not subject to the same uniqueness constraint. Maybe you can verify and include this detail as well?

**Comment by sbluhm** [comment]
@jsedding , thank you for your pointer. This indeed applies only to UUIDs. I just verified it. I have revised the statement and re-submitted.

**Comment by stefan-egli** [comment]
@jsedding do you think we should incorporate this PR?

**Comment by jsedding** [comment]
@stefan-egli yes, I think this is helpful information and should be applied!

@sbluhm sorry this fell between the cracks!

**Pull request merged**
