### PR TITLE
OAK-10051 attach correct artifact

### PR DESCRIPTION
**Pull request by kwin**
Use the one from m-assembly-p instead of the one from m-jar-p

### CODE REVIEW

**Comment by reschke** [comment]
Is there a simple way to test this?

**Comment by kwin** [comment]
Just execute `mvn install` on that module and look in the log which artifact is installed in the local repo.

**Comment by reschke** [comment]
Ah, good point.

**Review by reschke — APPROVED** [review]
Looks good to me.

**Pull request merged**
