### PR TITLE
OAK-9352 : move SystemPropertySupplier to commons 

### PR DESCRIPTION
**Pull request by stefan-egli**
Suggested implementation for a move:
* move the class, a negative: the package version of oak-commons must be increased
* make the original a deprecated facade

### CODE REVIEW

**Comment by ShangwenWang** [comment]
I also encounter build failures in my PR.
Do you know how to deal with it?

**Comment by stefan-egli** [comment]
The error reported is:
```
$ docker pull trekawek/azurite

Using default tag: latest

latest: Pulling from trekawek/azurite

anyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

The command "docker pull trekawek/azurite" failed and exited with 1 during .
```

So might be a temporary problem only, not sure

**Comment by stefan-egli** [comment]
Updated this PR with https://github.com/apache/jackrabbit-oak/pull/271/commits/2ff9b1a88ceab4e2f64fbb03c142dd13e9fab95e to instead move SystemPropertySupplier in its own, new package to avoid any versioning update troubles

**Comment by stefan-egli** [comment]
Merged in
* http://svn.apache.org/viewvc?rev=1886654&view=rev
* http://svn.apache.org/viewvc?rev=1886657&view=rev

**Pull request closed without merging**
