### PR TITLE
OAK-10413: DocumentStoreIndexerIT hanging

### PR DESCRIPTION
**Pull request by mreutegg**
Release resources held by Persistence

### CODE REVIEW

**Review by rishabhdaim — APPROVED** [review]
Shouldn't we also need to delete the folders created by `createFolders()`.

**Comment by mreutegg** [comment]
> Shouldn't we also need to delete the folders created by createFolders().

No. These are created via the JUnit Rule `TemporaryFolder` and automatically deleted at the end of the test.

**Comment by mreutegg** [comment]
Strange, now DocumentStoreIndexerIT showed a failure.
```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 90.811 s <<< FAILURE! - in org.apache.jackrabbit.oak.index.DocumentStoreIndexerIT
[ERROR] parallelReindexWithLZ4(org.apache.jackrabbit.oak.index.DocumentStoreIndexerIT)  Time elapsed: 24.515 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.junit.Assert.assertFalse(Assert.java:75)
	at org.apache.jackrabbit.oak.index.DocumentStoreIndexerIT.parallelReindexInternal(DocumentStoreIndexerIT.java:265)
	at org.apache.jackrabbit.oak.index.DocumentStoreIndexerIT.parallelReindexWithLZ4(DocumentStoreIndexerIT.java:184)
```
I'm not able to reproduce this on my machine. Maybe flaky? I'll update the branch to trigger a new build.

@tihom88, WDYT?

**Comment by mreutegg** [comment]
This time all tests ran successfully.

**Pull request merged**
