### PR TITLE
OAK-11269 add dedicated workflow for checking commit messages

### PR DESCRIPTION
**Pull request by kwin**
OAK-11269 my test

### CODE REVIEW

**Comment by Joscorbe** [comment]
This is a good idea, but got a question, will this check enforce the OAK-<ID> also in commits created by bots? I think that will fail in PRs like #1860

**Comment by kwin** [comment]
For now it is just a check which fails (on every PR which is not compliant). However there is nothing enforced right now, i.e. a failed check will not prevent merging via UI.

**Comment by Joscorbe** [comment]
> For now it is just a check which fails (on every PR which is not compliant). However there is nothing enforced right now, i.e. a failed check will not prevent merging via UI.

Sounds good, thanks!

**Comment by reschke** [comment]
@Joscorbe - re automatically generated PRs (such as from dependabot): these are useful, but IMHO we still should open a ticket (release notes!) and test things properly, so I would still prefer *us* creating the PR. In your example, the PR seems simple enough, but in fact breaks baseline, see https://issues.apache.org/jira/browse/OAK-11286?focusedCommentId=17901680&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17901680

**Review by reschke — APPROVED** [review]

**Pull request merged**
