### PR TITLE
OAK-10032 get rid of m-antrun-p to replace the main artifact

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Review by reschke — COMMENTED** [review]
I'm not a Maven expert. If it works, great.

I continue to believe that we should not make too many changes at once in a single commit, as it makes it harder to to track why something changed, what ticket it is related to do, and makes backports harder.

**Comment by kwin** [comment]
> I continue to believe that we should not make too many changes at once in a single commit, as it makes it harder to to track why something changed, what ticket it is related to do, and makes backports harder.

I don't think this is related to the PR, is it?

> I'm not a Maven expert. If it works, great.

Just try it out. It works good and I would consider my Maven knowledge pretty decent (FYI I am a committer there). Do you dare to approve or not, or should I involve anyone else in the review?

**Comment by reschke** [comment]
I will leave it to @nit0906 who's trying to release.

**Comment by reschke** [comment]
I tried the patch, and got past the oak-run issue. It's now failing later:

~~~
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (default) on project oak-run-elastic: An Ant BuildException has occured: Warning: Could not find file /home/jre/projects/apache/oak/trunk/oak-run-elastic/target/oak-run-elastic-1.45-SNAPSHOT-oak.jar to copy.
[ERROR] around Ant part ...<copy file="/home/jre/projects/apache/oak/trunk/oak-run-elastic/target/oak-run-elastic-1.45-SNAPSHOT-oak.jar" tofile="/home/jre/projects/apache/oak/trunk/oak-run-elastic/target/oak-run-elastic-1.45-SNAPSHOT.jar" />... @ 4:219 in /home/jre/projects/apache/oak/trunk/oak-run-elastic/target/antrun/build-main.xml
[ERROR] -> [Help 1]
~~~

**Comment by kwin** [comment]
The same fix has to applied to that module (i.e. remove antrun there and create primary artifact with m-assembly-p): https://github.com/apache/jackrabbit-oak/blob/c9a4070712e194a1b217aece1241b0afa10c414e/oak-run-elastic/pom.xml#L66-L117

**Comment by reschke** [comment]
I'll include these changes in the updated change for OAK-9800.

(Or would it make sense to apply them right away, with conflicts resolved...?)

**Comment by kwin** [comment]
For me these changes can and should be applied independently

**Comment by reschke** [comment]
Agreed; getting rid of the antrun step is valuable independant of the other changes. Testing right now.

**Pull request merged**
