### PR TITLE
OAK-10241: NPE while trying to get the BinaryDownload URI

### PR DESCRIPTION
**Pull request by mreutegg**
Add test and implement fix

### CODE REVIEW

**Review by mattvryan — APPROVED** [review]
LGTM, thank you @mreutegg !

**Comment by mreutegg** [comment]
Build failure in oak-blob-cloud-azure looks unrelated to this change.

**Comment by bhellema** [comment]
@mattvryan @mreutegg could we add some debug logging to spit out the name of the blob and path maybe that is being processed?  We are investigating an issue where the name we have been given doesn't match the name in the container storage causing an error.  Having this debug logging would be very beneficial.

**Comment by mreutegg** [comment]
@bhellema, can you please open a JIRA issue and describe where exactly you would like to have debug messages? Patches are also welcome ;)

**Pull request merged**
