### PR TITLE
OAK-10345 - Add debug log message if larger blob is compared byte-wise.

### PR DESCRIPTION
**Pull request by ahanikel**
We want to be able to assess how often it happens that large blobs are compared byte-by-byte.

### CODE REVIEW

**Review by dulceanu — CHANGES_REQUESTED** [review]
@ahanikel, I was thinking whether we could issue the log statement only when a boolean flag is set. I don't know if the current approach affects performance, but this way we could enable this only when needed.

**Comment by ahanikel** [comment]
@dulceanu Do you mean something like this?

**Review by reschke — CHANGES_REQUESTED** [review]
For reading system properties, please use oak-commons/src/main/java/org/apache/jackrabbit/oak/commons/properties/SystemPropertySupplier.java

**Comment by ahanikel** [comment]
@reschke Like this?

**Review by dulceanu — APPROVED** [review]

**Comment by ahanikel** [comment]
Actually it seems quite hard to set a system property if a feature toggle is enabled. Perhaps it's still easier to directly use a feature toggle instead of a system property?

**Review by reschke — APPROVED** [review]

**Pull request merged**
