### PR TITLE
OAK-9145: oak analyzer filters order

### PR DESCRIPTION
**Pull request by fabriziofortino**

### CODE REVIEW

**Comment by dlh3** [comment]
Relates to #242.

**Review by thomasmueller — APPROVED** [review]
LGTM

**Review by thomasmueller — CHANGES_REQUESTED** [review]
See comment in the oak issue.

**Comment by fabriziofortino** [comment]
See [OAK-9145 comment](https://issues.apache.org/jira/browse/OAK-9145?focusedCommentId=17278672&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17278672) for details this PR cannot be merged.

**Pull request closed without merging**
