### PR TITLE
OAK-9775 : ACEs with unsupported restrictions must be cleared upon editing, OAK-9782 : CompositeRestrictionProvider must call validate on aggregated providers

### PR DESCRIPTION
**Pull request by anchela**

### CODE REVIEW

**Comment by anchela** [comment]
@joerghoh , as discussed in private. don't know why i can't send you an review-invite through the 'reviewers' field. but your feedback would be very much appreciated as always.

**Comment by mreutegg** [comment]
> don't know why i can't send you an review-invite through the 'reviewers' field

I think this is because Joerg is not a Jackrabbit committer.

**Comment by anchela** [comment]
@mreutegg , @reschke , @joerghoh , unless you have any review findings, i would like to merge the changes.
one general question: oak-blob-plugins  and oak-webapp failed in the checks below and i am pretty sure it is unrelated to my changes. it is ok to ignore that?

**Comment by anchela** [comment]
@mreutegg , @reschke , additionally included a fix for OAK-9782 and additional tests verifying that OAK-9775 is also addressed in case of multiple restriction providers are aggregated.
will leave the PR open until start of next week to give you another chance to take a look.

**Comment by mreutegg** [comment]
I won't have time to reviw the changes this week and will be away next week. Maybe some other committer can review?

**Pull request merged**
