### PR TITLE
OAK-9359 : use SystemPropertySupplier to facilitate OAK-9134 backport

### PR DESCRIPTION
**Pull request by stefan-egli**

### CODE REVIEW

**Comment by stefan-egli** [comment]
Test failure :
```
org.osgi.framework.BundleException: 
  Unable to resolve org.apache.jackrabbit.oak-solr-osgi [22](R 22.0): 
  missing requirement [org.apache.jackrabbit.oak-solr-osgi [22](R 22.0)] 
  osgi.wiring.package; (osgi.wiring.package=org.apache.jackrabbit.oak.plugins.index.aggregate)
  [caused by: Unable to resolve org.apache.jackrabbit.oak-core [32](R 32.0): 
  missing requirement [org.apache.jackrabbit.oak-core [32](R 32.0)] 
  osgi.wiring.package; (osgi.wiring.package=org.apache.jackrabbit.oak.commons.properties)] 
  Unresolved requirements: [[org.apache.jackrabbit.oak-solr-osgi [22](R 22.0)] 
  osgi.wiring.package; (osgi.wiring.package=org.apache.jackrabbit.oak.plugins.index.aggregate)]
```

**Comment by mreutegg** [comment]
https://issues.apache.org/jira/browse/OAK-8707 introduced a whitelist of exported packages in the oak-commons pom.xml. The new package must be listed there as well.

**Comment by stefan-egli** [comment]
Thx @mreutegg , I just noticed those exported packages as well and fixed in https://github.com/apache/jackrabbit-oak/pull/278/commits/091ede53b394a48bd8e0ca86c6b5cd8905f20810

**Comment by stefan-egli** [comment]
* committed to trunk in rev [1887105](http://svn.apache.org/viewvc?rev=1887105&view=rev)

**Pull request closed without merging**
