### PR TITLE
OAK-10812: DocumentNodeStore#diffManyChildren(...) may produce incorr…

### PR DESCRIPTION
**Pull request by mbaedke**
…ect results in readonly mode

Added test case.

### CODE REVIEW

**Comment by mbaedke** [comment]
Preliminary test. Please review if it makes any sense.

**Review by stefan-egli — APPROVED** [review]
+1 for adding the test. It indeed highlights the problem in `Utils.getMinTimestampForDiff` ie in `RevisionVector.difference when in read-only mode.

Perhaps we can migrate it to use the virtual clock before the test gets unignored.

**Comment by mbaedke** [comment]
Potential fix: if in DocumentNodeStore#getMinExternalRevisions() we replace getClusterId() - which is 0 in readonly mode - with the configured cluster id, the problem disappears.

**Comment by stefan-egli** [comment]
I'm wondering if that wouldn't introduce a regression elsewhere .. there must have been a reason this was set to 0 for read-only?

**Comment by mbaedke** [comment]
@stefan-egli , I understand that it's not supposed to collide with a simultaneously running read-write node. The proposal is not to change the cluster id, but to add an additional property to store the configured cluster id.
That would probably not cover all scenarios, though, because the real cluster id may differ from the configured one.

**Comment by stefan-egli** [comment]
(maybe we could add a test case to reproduce real being different than configured id - and then the result might be two additional properties would be required, real and configured..)

**Comment by mbaedke** [comment]
@stefan-egli , see ticket for an explanation.

**Comment by stefan-egli** [comment]
PS: [commented](https://issues.apache.org/jira/browse/OAK-10812?focusedCommentId=17852849&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17852849) on the ticket

**Comment by ionutzpi** [comment]
@mbaedke adding a check to handle the case where fromRev.pmin(minRevisions) results in an empty vector could fix the issue

**Review by reschke — COMMENTED** [review]
I really can't comment without diving deep into this area.

**Pull request merged**
