### PR TITLE
OAK-9128: s3Connector changes for regions apart from aws default regions

### PR DESCRIPTION
**Pull request by neerajgrg**

### CODE REVIEW

**Comment by amit-jain** [comment]
@neerajgrg The changes lgtm. But have you run the full suite of tests? I would expect that the testing is done for atleast eu_ireland, us standard and one other maybe singapore.

**Comment by neerajgrg** [comment]
@amit-jain  Have run the test file TestS3DSWithSSES3 with eu_ireland, us standard and singapore region. All the test cases are working fine in this class. Please let me know if any other test cases needed to run

**Comment by amit-jain** [comment]
@neerajgrg Yes please run all tests not just this class.

**Comment by neerajgrg** [comment]
@amit-jain  All test cases are working fine.

**Comment by neerajgrg** [comment]
tested with all three regions eu_ireland, us standard and  singapore.

**Comment by amit-jain** [comment]
Thanks @neerajgrg for confirming, will take over.

**Review by amit-jain — APPROVED** [review]

**Comment by amit-jain** [comment]
@neerajgrg is there a jira issue associated with the PR? Please create one if not available.

**Comment by neerajgrg** [comment]
@amit-jain  can you please direct me to jira dashboard where should i create this jira ?

**Comment by amit-jain** [comment]
Created https://issues.apache.org/jira/browse/OAK-9128

**Comment by amit-jain** [comment]
Patch committed. Thanks! @neerajgrg this PR can be closed now.

**Comment by neerajgrg** [comment]
Thanks @amit-jain  I need this patch for AEM 6.5, for that i think we need to merge this path in branch 1.10 as well. Please let me know do i raise a new pull request for that?

**Comment by reschke** [comment]
1.22, not1.10 (1.10 is retired)

**Comment by neerajgrg** [comment]
okay, have a raised a pull request on 1.22 - https://github.com/apache/jackrabbit-oak/pull/237 . @amit-jain  please review

**Comment by amit-jain** [comment]
Don't need a PR for it, will merge from trunk.

**Comment by mreutegg** [comment]
Change has been committed to SVN: http://svn.apache.org/viewvc?rev=1879352&view=rev

**Pull request closed without merging**
