### PR TITLE
OAK-10472 - Move ApproximateCounter from oak-core to a place where it…

### PR DESCRIPTION
**Pull request by dulceanu**
… can be used by oak-segment-tar

### CODE REVIEW

**Review by reschke — CHANGES_REQUESTED** [review]
That split o.a.j.oak.plugins.index between two projects; technically this may not be a problem, but it might create confusion.

Proposal:

1. Short term: just copy ApproximateCounter into oak-segment-tar (under a different package name), so we can release 1.58.0 without public API changes.
2. Mid-term: decide what do do with org.apache.jackrabbit.oak.plugins.index - should it all go into oak-store-spi?

cc @mreutegg and @anchela

**Comment by dulceanu** [comment]
@reschke, I made the changes proposed. Can you please take another look?

**Comment by reschke** [comment]
Thanks a lot. I will update the issue description; open a new ticket regarding future refactoring and add a note to the copied class pointing to that new issue.

Thanks for the qucik feedback!

**Comment by reschke** [comment]
Overtaken by events; see https://github.com/apache/jackrabbit-oak/commit/c747535b9274403f4d56a15ebf25aadd109700d0 - thanks @dulceanu for the quick feedback.

**Pull request closed without merging**
